#!/usr/bin/env bash

# This is very simple build setup, the long-term goal is to move this off
# Docker Hub.
ALPINE_VERSION="3.7"
PHP_VERSION="7.2"
NGINX_VERSION="1.13"

PHP_TYPE=""
if [[ ${IMAGE_NAME} = *"fpm"* ]]; then
  PHP_TYPE="fpm"
elif [[ ${IMAGE_NAME} = *"cli"* ]]; then
  PHP_TYPE="cli"
fi

docker build -t ${IMAGE_NAME} -f ${DOCKERFILE_PATH} --build-arg=ALPINE_VERSION=${ALPINE_VERSION} --build-arg=PHP_VERSION=${PHP_VERSION} --build-arg=PHP_TYPE=${PHP_TYPE} .
